# version: '3.8'

# services:
#   php:
#     image: php:8.2-apache
#     container_name: php-app
#     ports:
#       - "8000:80"
#     volumes:
#       - .:/var/www/html
#     depends_on:
#       - db

#   db:
#     image: mysql:8.0
#     container_name: mysql-db
#     restart: always
#     environment:
#       MYSQL_ROOT_PASSWORD: root123
#       MYSQL_DATABASE: dailyexpense
#       MYSQL_USER: user
#       MYSQL_PASSWORD: pass123
#     ports:
#       - "3306:3306"
#     volumes:
#       - db_data:/var/lib/mysql

# volumes:
#   db_data:
services:
  php:
    build: .
    ports:
      - "${PHP_APP_PORT:-9000}:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: dailyexpense
      MYSQL_USER: user
      MYSQL_PASSWORD: pass123
    # ports: removed - no need to expose MySQL to host
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: